import { GenerateCaseStudyRequest } from '../types/case'

export function buildDefaultCaseStudyPrompt(data: GenerateCaseStudyRequest): string {
  return `Create a professional, detailed case study for UCtel (mobile signal boosting company) with the following information:\n\nClient: ${data.clientName}\nIndustry: ${data.industry}\nChallenge: ${data.mainChallenge}\nSolution: ${data.solutionProvided}\n${data.location ? `Location: ${data.location}` : ''}\n${data.projectScale ? `Scale: ${data.projectScale}` : ''}\n${data.technologiesUsed ? `Technologies: ${data.technologiesUsed}` : ''}\n${data.additionalContext ? `Additional Context: ${data.additionalContext}` : ''}\n\nGenerate a comprehensive case study with these exact sections (write substantial content for each - minimum 3-4 paragraphs per section):\n\n**SUMMARY**\nWrite 3-4 detailed paragraphs explaining: the client's situation, the specific connectivity challenges they faced, UCtel's solution approach, and the overall impact/results achieved. Make it engaging and comprehensive.\n\n**THE CLIENT**\nWrite 2-3 paragraphs describing: the client organization in detail, their industry position, location specifics, size/scale, what makes them unique, and why reliable connectivity was crucial for their operations.\n\n**THE CHALLENGES**\nWrite 4-5 paragraphs detailing: specific technical connectivity issues, coverage problems, user impact, business consequences, any unique environmental factors, regulatory considerations, and why these challenges were particularly difficult for this client.\n\n**THE SOLUTION**\nWrite 4-5 paragraphs explaining: UCtel's technical approach, specific equipment used (CEL-FI models, antenna systems, etc.), installation process, technical specifications, implementation timeline, partnerships involved, and why this solution was optimal for their needs.\n\n**THE RESULTS**\nWrite 3-4 paragraphs covering: specific improvements achieved, measurable results, user feedback, business benefits, implementation timeline, client satisfaction, and any future-looking statements or calls to action.\n\n**SIDEBAR_CHALLENGE**\nWrite 2-3 sentences summarizing the main connectivity challenge for the sidebar.\n\n**SIDEBAR_RESULTS**\nWrite 2-3 sentences summarizing the key results and benefits achieved for the sidebar.\n\n**CLIENT_QUOTE**\nCreate a realistic, compelling quote from the client expressing satisfaction with UCtel's solution and its business impact.\n\nWrite in a professional, technical tone suitable for B2B audiences. Use specific technical terms, mention measurable improvements, and include concrete details. Each section should be substantial and informative, similar to UCtel's existing case studies.`
}

export function buildDefaultImagePrompt(data: GenerateCaseStudyRequest): string {
  return `Professional exterior photograph of ${data.clientName} building in ${data.location || 'modern urban setting'}, ${data.industry} sector, corporate architecture, high quality, business photography style`
}
